apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: cmonthe8/weather-service:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # env: # Add the ConfigMap-based environment variable here
        # - name: OPEN_METEO_URL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: weather-config # Name of the ConfigMap
        #       key: OPEN_METEO_URL  # Key in the ConfigMap
        # readinessProbe:
        #   httpGet:
        #     path: /weather
        #     port: 5000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /weather
        #     port: 5000
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
