apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Port on the Service
      targetPort: 5000  # Port the application listens on
      nodePort: 30007   # Fixed port (optional, or leave blank for automatic assignment)

